<?php
  session_start();
  include_once '..\includes\dbConnector.php';
  $id=$_POST['id'];
  $pwd=$_POST['pwd'];
  $sql="SELECT pwd,UID,Username,User_type FROM profile where Email='$id' OR username='$id'";
  $result=mysqli_query($conn,$sql);
  if($result->num_rows==0){
    header("Location:../index.php?feedback=null");
  }
  else{
    $row=mysqli_fetch_assoc($result);
    if($pwd==$row['pwd']){
      $_SESSION['UID']=$row['UID'];
      $_SESSION['Username']=$row['Username'];
      $_SESSION['User_type']=$row['User_type'];
      if($row['User_type']=='norm'){
        header("Location:../dashboard.php");
      }
      else{
        header("Location:../upload.php");
      }
    }
    else{
      header("Location:../index.php?feedback=invalid");
      session_destroy();
    }
  }
?>
